const API='/api/v1';
const state={view:'dashboard',containers:[],images:[],system:null};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const response=await fetch(API+path,options);if(!response.ok){let message=response.statusText;try{message=(await response.json()).error.message}catch{}throw new Error(message)}if(response.status===204)return null;const type=response.headers.get('content-type')||'';return type.includes('json')?response.json():response.text()}
function toast(message,type=''){const node=$('#toast');node.textContent=message;node.className='show '+type;setTimeout(()=>node.className='',2800)}
function badge(status){return `<span class="badge ${esc(status)}">${esc(status)}</span>`}
function stat(label,value){return `<div class="stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function duration(seconds){if(!seconds)return '-';if(seconds<60)return seconds+' 秒';if(seconds<3600)return Math.floor(seconds/60)+' 分钟';return Math.floor(seconds/3600)+' 小时'}
async function load(){try{[state.containers,state.images,state.system]=await Promise.all([api('/containers'),api('/images'),api('/system/info')]);$('#connection').textContent='运行时在线';$('#connection').className='connection online';render()}catch(error){$('#connection').textContent='连接失败';$('#connection').className='connection';toast(error.message,'error')}}
function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view));const names={dashboard:'概览',containers:'容器',images:'镜像',import:'导入镜像',create:'创建容器'};$('#title').textContent=names[state.view]||'mini-container';({dashboard:renderDashboard,containers:renderContainers,images:renderImages,import:renderImport,create:renderCreate}[state.view]||renderDashboard)()}
function renderDashboard(){const running=state.containers.filter(c=>c.status==='running').length;const exited=state.containers.filter(c=>c.status==='exited').length;const info=state.system||{};$('#content').innerHTML=`<div class="stats">${stat('容器总数',state.containers.length)}${stat('运行中',running)}${stat('已退出',exited)}${stat('镜像',state.images.length)}</div><div class="system"><div><span>CGROUP</span>v${info.cgroupVersion||'不可用'}</div><div><span>内核</span>${esc(info.kernel||'-')}</div><div><span>GO</span>${esc(info.goVersion||'-')}</div><div><span>状态目录</span>${esc(info.stateDir||'-')}</div><div><span>子网</span>${esc(info.subnet||'-')}</div><div><span>平台状态</span>${info.cgroupVersion?'可运行容器':'仅管理与构建'}</div></div>`}
function containerRow(c){const start=c.status==='created'||c.status==='exited';const stop=c.status==='running';return `<tr><td><button class="link" onclick="detail('${c.id}')">${esc(c.name)}</button><div class="mono">${esc(c.id.slice(0,8))}</div></td><td>${esc(c.image)}</td><td>${badge(c.status)}</td><td>${esc(c.ip||'-')}</td><td>${duration(c.runtimeSeconds)}</td><td><div class="actions"><button title="启动" ${start?'':'disabled'} onclick="action('${c.id}','start')">&#9654;</button><button title="停止" ${stop?'':'disabled'} onclick="action('${c.id}','stop')">&#9632;</button><button title="日志" onclick="logs('${c.id}')">日志</button><button class="danger" title="删除" onclick="removeContainer('${c.id}')">&#215;</button></div></td></tr>`}
function renderContainers(){const rows=state.containers.map(containerRow).join('');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="go('create')">+ 创建容器</button><span class="spacer"></span><input id="search" placeholder="搜索名称或 ID" oninput="filterRows(this.value)"></div>${rows?`<div class="table-wrap"><table><thead><tr><th>容器</th><th>镜像</th><th>状态</th><th>IP</th><th>运行时间</th><th>操作</th></tr></thead><tbody id="container-rows">${rows}</tbody></table></div>`:'<div class="empty">还没有容器</div>'}`}
function filterRows(value){const term=value.toLowerCase();document.querySelectorAll('#container-rows tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(term))}
function renderImages(){const rows=state.images.map(i=>`<tr><td><strong>${esc(i.name)}</strong><div class="mono">${esc(i.id)}</div></td><td>${i.layers.length}</td><td>${(i.sizeBytes/1024/1024).toFixed(2)} MB</td><td>${i.refCount}</td><td><div class="actions"><a class="button" href="${API}/images/${encodeURIComponent(i.name)}/export">导出</a><button class="danger" onclick="removeImage('${esc(i.name)}')">&#215;</button></div></td></tr>`).join('');$('#content').innerHTML=`<div class="toolbar"><button class="primary" onclick="go('import')">+ 导入镜像</button></div>${rows?`<div class="table-wrap"><table><thead><tr><th>镜像</th><th>层数</th><th>大小</th><th>引用</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="empty">先导入一个本地镜像 tar 包</div>'}`}
function renderImport(){$('#content').innerHTML=`<div class="drop"><h2>导入本地镜像</h2><p>选择包含 manifest.json 与层目录的 tar 包</p><input id="image-file" type="file" accept=".tar"><div class="progress"><i id="bar"></i></div><p><button class="primary" onclick="uploadImage()">导入</button></p></div>`}
function renderCreate(){const options=state.images.map(i=>`<option value="${esc(i.name)}">${esc(i.name)}</option>`).join('');$('#content').innerHTML=`<form class="form" onsubmit="submitCreate(event)"><div class="form-grid"><div class="field"><label>名称</label><input name="name" placeholder="自动生成"></div><div class="field"><label>镜像</label><select name="image" required><option value="">选择镜像</option>${options}</select></div><div class="field full"><label>命令</label><input name="cmd" value="/bin/sh -c 'sleep 3600'" required></div><div class="field"><label>Hostname</label><input name="hostname"></div><div class="field"><label>网络</label><select name="networkMode"><option value="bridge">bridge</option><option value="host">host</option></select></div><div class="field"><label>CPU 配额</label><input name="cpuQuota" type="number" min="0" step="0.1" value="0"></div><div class="field"><label>内存 MB</label><input name="memoryMB" type="number" min="0" value="256"></div><div class="field"><label>PIDs 上限</label><input name="pidsLimit" type="number" min="0" value="128"></div><div class="field"><label>退出即删</label><input name="autoRemove" type="checkbox"></div></div><div><button class="primary" ${options?'':'disabled'}>创建容器</button></div></form>`}
async function submitCreate(event){event.preventDefault();const form=new FormData(event.target);const body={name:form.get('name'),image:form.get('image'),cmd:['/bin/sh','-c',form.get('cmd')],hostname:form.get('hostname'),networkMode:form.get('networkMode'),resources:{cpuShares:1024,cpuQuota:Number(form.get('cpuQuota')),memoryMB:Number(form.get('memoryMB')),pidsLimit:Number(form.get('pidsLimit'))},mounts:[],env:[],autoRemove:form.get('autoRemove')==='on'};try{await api('/containers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('容器已创建');go('containers');await load()}catch(error){toast(error.message,'error')}}
async function action(id,name){try{await api(`/containers/${id}/${name}`,{method:'POST'});toast(name==='start'?'容器已启动':'容器已停止');await load()}catch(error){toast(error.message,'error')}}
async function removeContainer(id){if(!confirm('删除此容器及其可写层？'))return;try{await api('/containers/'+id,{method:'DELETE'});toast('容器已删除');await load()}catch(error){toast(error.message,'error')}}
async function removeImage(name){if(!confirm('删除镜像 '+name+'？'))return;try{await api('/images/'+encodeURIComponent(name),{method:'DELETE'});toast('镜像已删除');await load()}catch(error){toast(error.message,'error')}}
async function detail(id){try{const c=await api('/containers/'+id);$('#modal-body').innerHTML=`<h2>${esc(c.name)}</h2><p>${badge(c.status)} <span class="mono">${esc(c.id)}</span></p><div class="system"><div><span>镜像</span>${esc(c.image)}</div><div><span>IP</span>${esc(c.ip||'-')}</div><div><span>PID</span>${c.pid||'-'}</div><div><span>CPU</span>${c.stats?.cpuUsagePercent??'-'}%</div><div><span>内存</span>${c.stats?.memoryUsedMB??'-'} MB</div><div><span>PIDs</span>${c.stats?.pidsCurrent??'-'}</div></div><h3>命令</h3><pre>${esc(c.cmd.join(' '))}</pre>`;$('#modal').showModal()}catch(error){toast(error.message,'error')}}
async function logs(id){try{const text=await api(`/containers/${id}/logs?tail=200`);$('#modal-body').innerHTML=`<h2>容器日志</h2><pre>${esc(text)||'暂无日志'}</pre>`;$('#modal').showModal()}catch(error){toast(error.message,'error')}}
function uploadImage(){const input=$('#image-file');if(!input.files[0]){toast('请选择 tar 文件','error');return}const form=new FormData();form.append('file',input.files[0]);const xhr=new XMLHttpRequest();xhr.open('POST',API+'/images/import');xhr.upload.onprogress=e=>{if(e.lengthComputable)$('#bar').style.width=(e.loaded/e.total*100)+'%'};xhr.onload=async()=>{if(xhr.status<300){toast('镜像导入完成');go('images');await load()}else{toast(xhr.responseText,'error')}};xhr.onerror=()=>toast('上传失败','error');xhr.send(form)}
function go(view){state.view=view;render()}
document.querySelectorAll('.nav').forEach(node=>node.onclick=()=>go(node.dataset.view));$('#refresh').onclick=load;
const events=new EventSource(API+'/system/events');events.onmessage=()=>load();events.onerror=()=>{$('#connection').textContent='事件流重连中';$('#connection').className='connection'};
window.go=go;window.action=action;window.removeContainer=removeContainer;window.removeImage=removeImage;window.detail=detail;window.logs=logs;window.uploadImage=uploadImage;window.submitCreate=submitCreate;window.filterRows=filterRows;
load();setInterval(load,10000);
